/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example;

/**
 *
 * @author Michelle Khadan
 */
public class ExamPage extends javax.swing.JFrame {

    /**
     * Creates new form QuestionsPage
     */
    public ExamPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupExamSort1 = new javax.swing.ButtonGroup();
        buttonGroupExamSort2 = new javax.swing.ButtonGroup();
        navBar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageBrowseTabs = new javax.swing.JTabbedPane();
        managePanel = new javax.swing.JPanel();
        controlsPanel = new javax.swing.JPanel();
        savebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        generatequestionbutton = new javax.swing.JButton();
        exportbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        examTitlePanel = new javax.swing.JPanel();
        examTitleTextField = new javax.swing.JTextField();
        managePanelOptionsTab = new javax.swing.JTabbedPane();
        filterPanel = new javax.swing.JPanel();
        usedFilterOptions = new javax.swing.JPanel();
        usedYes = new javax.swing.JCheckBox();
        usedNo = new javax.swing.JCheckBox();
        difficultyFilterOptions = new javax.swing.JPanel();
        difficultyEasy = new javax.swing.JCheckBox();
        difficultyMedium = new javax.swing.JCheckBox();
        difficultyHard = new javax.swing.JCheckBox();
        courseFilterOptions = new javax.swing.JPanel();
        courseComboBox = new javax.swing.JComboBox<>();
        topicFilterOptions = new javax.swing.JPanel();
        topicComboBox = new javax.swing.JComboBox<>();
        subTopicFilterOptions = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        sortpanel = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        addedquestionspanel = new javax.swing.JPanel();
        examTagsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        questionSelectionPanel = new javax.swing.JPanel();
        searchBarQuestionSelectionPanel = new javax.swing.JPanel();
        jTextField16 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        previewAnswerPanel = new javax.swing.JPanel();
        browsePanel = new javax.swing.JPanel();
        searchBarExamsPanel = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        browsePanelOptionsPanel = new javax.swing.JPanel();
        browsePanelOptionsTab = new javax.swing.JTabbedPane();
        filterPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        administeredFilterOptions = new javax.swing.JPanel();
        adminsteredYes = new javax.swing.JCheckBox();
        administeredNo = new javax.swing.JCheckBox();
        gradedFilterOptions = new javax.swing.JPanel();
        gradedYes = new javax.swing.JCheckBox();
        gradedNo = new javax.swing.JCheckBox();
        courseFilterOptions2 = new javax.swing.JPanel();
        courseComboBox2 = new javax.swing.JComboBox<>();
        sortPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        searchResultsExamBrowsePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navBar.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Return");
        navBar.add(jButton1, java.awt.BorderLayout.LINE_START);

        jButton2.setText("Help");
        navBar.add(jButton2, java.awt.BorderLayout.LINE_END);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exams");
        navBar.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(navBar, java.awt.BorderLayout.PAGE_START);

        controlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        savebutton.setText("Save");
        controlsPanel.add(savebutton);

        clearbutton.setText("Clear");
        controlsPanel.add(clearbutton);

        generatequestionbutton.setText("Generate Questions");
        generatequestionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatequestionbuttonActionPerformed(evt);
            }
        });
        controlsPanel.add(generatequestionbutton);

        exportbutton.setText("Export");
        exportbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportbuttonActionPerformed(evt);
            }
        });
        controlsPanel.add(exportbutton);

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        controlsPanel.add(deletebutton);

        examTitlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Exam Title"));

        examTitleTextField.setText("Exam Title Text");
        examTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examTitleTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout examTitlePanelLayout = new javax.swing.GroupLayout(examTitlePanel);
        examTitlePanel.setLayout(examTitlePanelLayout);
        examTitlePanelLayout.setHorizontalGroup(
            examTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(examTitleTextField)
                .addContainerGap())
        );
        examTitlePanelLayout.setVerticalGroup(
            examTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examTitlePanelLayout.createSequentialGroup()
                .addComponent(examTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        managePanelOptionsTab.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        usedFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Used"));

        usedYes.setText("Yes");

        usedNo.setText("No");

        javax.swing.GroupLayout usedFilterOptionsLayout = new javax.swing.GroupLayout(usedFilterOptions);
        usedFilterOptions.setLayout(usedFilterOptionsLayout);
        usedFilterOptionsLayout.setHorizontalGroup(
            usedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usedFilterOptionsLayout.createSequentialGroup()
                .addGroup(usedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usedYes)
                    .addComponent(usedNo))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        usedFilterOptionsLayout.setVerticalGroup(
            usedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usedFilterOptionsLayout.createSequentialGroup()
                .addComponent(usedYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usedNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        difficultyFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Difficulty"));

        difficultyEasy.setText("Easy");

        difficultyMedium.setText("Medium");

        difficultyHard.setText("Hard");
        difficultyHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyHardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout difficultyFilterOptionsLayout = new javax.swing.GroupLayout(difficultyFilterOptions);
        difficultyFilterOptions.setLayout(difficultyFilterOptionsLayout);
        difficultyFilterOptionsLayout.setHorizontalGroup(
            difficultyFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyFilterOptionsLayout.createSequentialGroup()
                .addGroup(difficultyFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difficultyEasy)
                    .addComponent(difficultyHard)
                    .addComponent(difficultyMedium))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        difficultyFilterOptionsLayout.setVerticalGroup(
            difficultyFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyFilterOptionsLayout.createSequentialGroup()
                .addComponent(difficultyEasy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyHard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        courseFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        javax.swing.GroupLayout courseFilterOptionsLayout = new javax.swing.GroupLayout(courseFilterOptions);
        courseFilterOptions.setLayout(courseFilterOptionsLayout);
        courseFilterOptionsLayout.setHorizontalGroup(
            courseFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        courseFilterOptionsLayout.setVerticalGroup(
            courseFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        topicFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Topic"));

        topicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Topic 1", "Topic 2", "Topic 3", "Topic 4" }));

        javax.swing.GroupLayout topicFilterOptionsLayout = new javax.swing.GroupLayout(topicFilterOptions);
        topicFilterOptions.setLayout(topicFilterOptionsLayout);
        topicFilterOptionsLayout.setHorizontalGroup(
            topicFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topicFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topicComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        topicFilterOptionsLayout.setVerticalGroup(
            topicFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topicFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subTopicFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Sub-Topic"));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub-Topic 1", "Sub-Topic 2", "Sub-Topic 3", "Sub-Topic 4" }));

        javax.swing.GroupLayout subTopicFilterOptionsLayout = new javax.swing.GroupLayout(subTopicFilterOptions);
        subTopicFilterOptions.setLayout(subTopicFilterOptionsLayout);
        subTopicFilterOptionsLayout.setHorizontalGroup(
            subTopicFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTopicFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, 0, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        subTopicFilterOptionsLayout.setVerticalGroup(
            subTopicFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTopicFilterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usedFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difficultyFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topicFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subTopicFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usedFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topicFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTopicFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        managePanelOptionsTab.addTab("Filter", filterPanel);

        buttonGroupExamSort1.add(jRadioButton8);
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("Default");

        buttonGroupExamSort1.add(jRadioButton9);
        jRadioButton9.setText("Images First");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroupExamSort1.add(jRadioButton10);
        jRadioButton10.setText("Text First");

        buttonGroupExamSort1.add(jRadioButton11);
        jRadioButton11.setText("Last Used (Oldest First)");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroupExamSort1.add(jRadioButton12);
        jRadioButton12.setText("Last Used (Newest First)");

        buttonGroupExamSort1.add(jRadioButton13);
        jRadioButton13.setText("Date Created (Oldest First)");

        buttonGroupExamSort1.add(jRadioButton14);
        jRadioButton14.setText("Date Created (Newest First)");

        buttonGroupExamSort1.add(jRadioButton15);
        jRadioButton15.setText("Times Used (Least First)");

        buttonGroupExamSort1.add(jRadioButton16);
        jRadioButton16.setText("Times Used (Most First)");

        buttonGroupExamSort1.add(jRadioButton17);
        jRadioButton17.setText("Difficulty (Easy First)");

        buttonGroupExamSort1.add(jRadioButton18);
        jRadioButton18.setText("Difficulty (Hard First)");

        javax.swing.GroupLayout sortpanelLayout = new javax.swing.GroupLayout(sortpanel);
        sortpanel.setLayout(sortpanelLayout);
        sortpanelLayout.setHorizontalGroup(
            sortpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        sortpanelLayout.setVerticalGroup(
            sortpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton18)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        managePanelOptionsTab.addTab("Sort", sortpanel);

        javax.swing.GroupLayout addedquestionspanelLayout = new javax.swing.GroupLayout(addedquestionspanel);
        addedquestionspanel.setLayout(addedquestionspanelLayout);
        addedquestionspanelLayout.setHorizontalGroup(
            addedquestionspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        addedquestionspanelLayout.setVerticalGroup(
            addedquestionspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        managePanelOptionsTab.addTab("Added Questions", addedquestionspanel);

        jLabel2.setText("Date Created:");

        jFormattedTextField1.setText("DD/MM/YYYY");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Date Administered:");

        jFormattedTextField2.setText("DD/MM/YYYY");
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Edited:");

        jFormattedTextField3.setText("DD/MM/YYYY");
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Performance:");

        jFormattedTextField4.setText("-%");
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout examTagsPanelLayout = new javax.swing.GroupLayout(examTagsPanel);
        examTagsPanel.setLayout(examTagsPanelLayout);
        examTagsPanelLayout.setHorizontalGroup(
            examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examTagsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(examTagsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(examTagsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(examTagsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(examTagsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        examTagsPanelLayout.setVerticalGroup(
            examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examTagsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(examTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        managePanelOptionsTab.addTab("Exam Tags", examTagsPanel);

        questionSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Question Selection"));

        searchBarQuestionSelectionPanel.setLayout(new java.awt.BorderLayout());

        jTextField16.setText("Search...");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        searchBarQuestionSelectionPanel.add(jTextField16, java.awt.BorderLayout.CENTER);

        jButton13.setText("Search");
        searchBarQuestionSelectionPanel.add(jButton13, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout questionSelectionPanelLayout = new javax.swing.GroupLayout(questionSelectionPanel);
        questionSelectionPanel.setLayout(questionSelectionPanelLayout);
        questionSelectionPanelLayout.setHorizontalGroup(
            questionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBarQuestionSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        questionSelectionPanelLayout.setVerticalGroup(
            questionSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionSelectionPanelLayout.createSequentialGroup()
                .addComponent(searchBarQuestionSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 293, Short.MAX_VALUE))
        );

        previewAnswerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview Answers"));

        javax.swing.GroupLayout previewAnswerPanelLayout = new javax.swing.GroupLayout(previewAnswerPanel);
        previewAnswerPanel.setLayout(previewAnswerPanelLayout);
        previewAnswerPanelLayout.setHorizontalGroup(
            previewAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        previewAnswerPanelLayout.setVerticalGroup(
            previewAnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout managePanelLayout = new javax.swing.GroupLayout(managePanel);
        managePanel.setLayout(managePanelLayout);
        managePanelLayout.setHorizontalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managePanelLayout.createSequentialGroup()
                        .addGroup(managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(previewAnswerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(managePanelOptionsTab)))
                .addContainerGap())
        );
        managePanelLayout.setVerticalGroup(
            managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(managePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePanelLayout.createSequentialGroup()
                        .addComponent(questionSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewAnswerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(managePanelOptionsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        managePanelOptionsTab.getAccessibleContext().setAccessibleName("Filter");

        manageBrowseTabs.addTab("Manage", managePanel);

        searchBarExamsPanel.setLayout(new java.awt.BorderLayout());

        jTextField15.setText("Search...");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        searchBarExamsPanel.add(jTextField15, java.awt.BorderLayout.CENTER);

        jButton12.setText("Search");
        searchBarExamsPanel.add(jButton12, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        administeredFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Administered"));

        adminsteredYes.setText("Yes");

        administeredNo.setText("No");

        javax.swing.GroupLayout administeredFilterOptionsLayout = new javax.swing.GroupLayout(administeredFilterOptions);
        administeredFilterOptions.setLayout(administeredFilterOptionsLayout);
        administeredFilterOptionsLayout.setHorizontalGroup(
            administeredFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administeredFilterOptionsLayout.createSequentialGroup()
                .addGroup(administeredFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminsteredYes)
                    .addComponent(administeredNo))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        administeredFilterOptionsLayout.setVerticalGroup(
            administeredFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administeredFilterOptionsLayout.createSequentialGroup()
                .addComponent(adminsteredYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administeredNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gradedFilterOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Graded"));

        gradedYes.setText("Yes");

        gradedNo.setText("No");

        javax.swing.GroupLayout gradedFilterOptionsLayout = new javax.swing.GroupLayout(gradedFilterOptions);
        gradedFilterOptions.setLayout(gradedFilterOptionsLayout);
        gradedFilterOptionsLayout.setHorizontalGroup(
            gradedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradedFilterOptionsLayout.createSequentialGroup()
                .addGroup(gradedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradedYes)
                    .addComponent(gradedNo))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gradedFilterOptionsLayout.setVerticalGroup(
            gradedFilterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradedFilterOptionsLayout.createSequentialGroup()
                .addComponent(gradedYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradedNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        courseFilterOptions2.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));

        courseComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "course1", "course2", "course3", "course4" }));

        javax.swing.GroupLayout courseFilterOptions2Layout = new javax.swing.GroupLayout(courseFilterOptions2);
        courseFilterOptions2.setLayout(courseFilterOptions2Layout);
        courseFilterOptions2Layout.setHorizontalGroup(
            courseFilterOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseFilterOptions2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseComboBox2, 0, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        courseFilterOptions2Layout.setVerticalGroup(
            courseFilterOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseFilterOptions2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administeredFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseFilterOptions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradedFilterOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(administeredFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradedFilterOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseFilterOptions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel14);

        javax.swing.GroupLayout filterPanel2Layout = new javax.swing.GroupLayout(filterPanel2);
        filterPanel2.setLayout(filterPanel2Layout);
        filterPanel2Layout.setHorizontalGroup(
            filterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        filterPanel2Layout.setVerticalGroup(
            filterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        browsePanelOptionsTab.addTab("Filter", filterPanel2);

        buttonGroupExamSort2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Default");

        buttonGroupExamSort2.add(jRadioButton2);
        jRadioButton2.setText("Date Administered (Oldest First)");

        buttonGroupExamSort2.add(jRadioButton3);
        jRadioButton3.setText("Date Administered (Newest First)");

        buttonGroupExamSort2.add(jRadioButton4);
        jRadioButton4.setText("Date Created (Oldest First)");

        buttonGroupExamSort2.add(jRadioButton5);
        jRadioButton5.setText("Date Created (Newest First)");

        buttonGroupExamSort2.add(jRadioButton6);
        jRadioButton6.setText("Performance (Lowest First)");

        buttonGroupExamSort2.add(jRadioButton7);
        jRadioButton7.setText("Performance (Highest First)");

        javax.swing.GroupLayout sortPanel2Layout = new javax.swing.GroupLayout(sortPanel2);
        sortPanel2.setLayout(sortPanel2Layout);
        sortPanel2Layout.setHorizontalGroup(
            sortPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sortPanel2Layout.setVerticalGroup(
            sortPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        browsePanelOptionsTab.addTab("Sort", sortPanel2);

        javax.swing.GroupLayout browsePanelOptionsPanelLayout = new javax.swing.GroupLayout(browsePanelOptionsPanel);
        browsePanelOptionsPanel.setLayout(browsePanelOptionsPanelLayout);
        browsePanelOptionsPanelLayout.setHorizontalGroup(
            browsePanelOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browsePanelOptionsTab)
        );
        browsePanelOptionsPanelLayout.setVerticalGroup(
            browsePanelOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browsePanelOptionsTab)
        );

        javax.swing.GroupLayout searchResultsExamBrowsePanelLayout = new javax.swing.GroupLayout(searchResultsExamBrowsePanel);
        searchResultsExamBrowsePanel.setLayout(searchResultsExamBrowsePanelLayout);
        searchResultsExamBrowsePanelLayout.setHorizontalGroup(
            searchResultsExamBrowsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        searchResultsExamBrowsePanelLayout.setVerticalGroup(
            searchResultsExamBrowsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout browsePanelLayout = new javax.swing.GroupLayout(browsePanel);
        browsePanel.setLayout(browsePanelLayout);
        browsePanelLayout.setHorizontalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBarExamsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addComponent(searchResultsExamBrowsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browsePanelOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        browsePanelLayout.setVerticalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browsePanelOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(browsePanelLayout.createSequentialGroup()
                        .addComponent(searchBarExamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchResultsExamBrowsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        manageBrowseTabs.addTab("Browse", browsePanel);

        getContentPane().add(manageBrowseTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void examTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examTitleTextFieldActionPerformed

    private void generatequestionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatequestionbuttonActionPerformed
        // TODO add your handling code here:
        GenerateQuestionForm popup = new GenerateQuestionForm(null, true); // 'true' makes it modal
        popup.setLocationRelativeTo(null); // Centers the popup
        popup.setVisible(true); // Show the form
    }//GEN-LAST:event_generatequestionbuttonActionPerformed

    private void exportbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void difficultyHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyHardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyHardActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addedquestionspanel;
    private javax.swing.JPanel administeredFilterOptions;
    private javax.swing.JCheckBox administeredNo;
    private javax.swing.JCheckBox adminsteredYes;
    private javax.swing.JPanel browsePanel;
    private javax.swing.JPanel browsePanelOptionsPanel;
    private javax.swing.JTabbedPane browsePanelOptionsTab;
    private javax.swing.ButtonGroup buttonGroupExamSort1;
    private javax.swing.ButtonGroup buttonGroupExamSort2;
    private javax.swing.JButton clearbutton;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JComboBox<String> courseComboBox2;
    private javax.swing.JPanel courseFilterOptions;
    private javax.swing.JPanel courseFilterOptions2;
    private javax.swing.JButton deletebutton;
    private javax.swing.JCheckBox difficultyEasy;
    private javax.swing.JPanel difficultyFilterOptions;
    private javax.swing.JCheckBox difficultyHard;
    private javax.swing.JCheckBox difficultyMedium;
    private javax.swing.JPanel examTagsPanel;
    private javax.swing.JPanel examTitlePanel;
    private javax.swing.JTextField examTitleTextField;
    private javax.swing.JButton exportbutton;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel filterPanel2;
    private javax.swing.JButton generatequestionbutton;
    private javax.swing.JPanel gradedFilterOptions;
    private javax.swing.JCheckBox gradedNo;
    private javax.swing.JCheckBox gradedYes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTabbedPane manageBrowseTabs;
    private javax.swing.JPanel managePanel;
    private javax.swing.JTabbedPane managePanelOptionsTab;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel previewAnswerPanel;
    private javax.swing.JPanel questionSelectionPanel;
    private javax.swing.JButton savebutton;
    private javax.swing.JPanel searchBarExamsPanel;
    private javax.swing.JPanel searchBarQuestionSelectionPanel;
    private javax.swing.JPanel searchResultsExamBrowsePanel;
    private javax.swing.JPanel sortPanel2;
    private javax.swing.JPanel sortpanel;
    private javax.swing.JPanel subTopicFilterOptions;
    private javax.swing.JComboBox<String> topicComboBox;
    private javax.swing.JPanel topicFilterOptions;
    private javax.swing.JPanel usedFilterOptions;
    private javax.swing.JCheckBox usedNo;
    private javax.swing.JCheckBox usedYes;
    // End of variables declaration//GEN-END:variables
}
