/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Rian Ramdin
 */
public class Questions extends javax.swing.JPanel {

    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        questionsLabel = new javax.swing.JLabel();
        questionsTabbedPane = new javax.swing.JTabbedPane();
        manageScrollTab = new javax.swing.JScrollPane();
        manageScrollContentPanel = new javax.swing.JPanel();
        manageControlsPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        manageQuestionPanel = new javax.swing.JPanel();
        questionTF = new javax.swing.JTextField();
        qImageCB = new javax.swing.JCheckBox();
        qImageButton = new javax.swing.JButton();
        imagePathTF = new javax.swing.JTextField();
        manageAnswersPanel = new javax.swing.JPanel();
        ansRadioButton1 = new javax.swing.JRadioButton();
        ansTF1 = new javax.swing.JTextField();
        ansImageCB1 = new javax.swing.JCheckBox();
        ansImageButton1 = new javax.swing.JButton();
        ansRadioButton2 = new javax.swing.JRadioButton();
        ansTF2 = new javax.swing.JTextField();
        ansImageCB2 = new javax.swing.JCheckBox();
        ansImageButton2 = new javax.swing.JButton();
        ansRadioButton3 = new javax.swing.JRadioButton();
        ansTF3 = new javax.swing.JTextField();
        ansImageCB3 = new javax.swing.JCheckBox();
        ansImageButton3 = new javax.swing.JButton();
        ansRadioButton4 = new javax.swing.JRadioButton();
        ansTF4 = new javax.swing.JTextField();
        ansImageCB4 = new javax.swing.JCheckBox();
        ansImageButton4 = new javax.swing.JButton();
        manageTagsPanel = new javax.swing.JPanel();
        tagsEditablePanel = new javax.swing.JPanel();
        courseLabel = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        topicLabel = new javax.swing.JLabel();
        topicComboBox = new javax.swing.JComboBox<>();
        subtopicLabel = new javax.swing.JLabel();
        subtopicComboBox = new javax.swing.JComboBox<>();
        difficultyLabel = new javax.swing.JLabel();
        difficultyComboBox = new javax.swing.JComboBox<>();
        tagsFiller = new javax.swing.Box.Filler(new java.awt.Dimension(40, 100), new java.awt.Dimension(40, 100), new java.awt.Dimension(40, 100));
        tagsNonEditablePanel = new javax.swing.JPanel();
        dateCreatedLabel = new javax.swing.JLabel();
        dateCreatedTF = new javax.swing.JTextField();
        dateEditedLabel = new javax.swing.JLabel();
        dateEditedTF = new javax.swing.JTextField();
        dateUsedLabel = new javax.swing.JLabel();
        dateUsedTF = new javax.swing.JTextField();
        usedCountLabel = new javax.swing.JLabel();
        usedCountTF = new javax.swing.JTextField();
        perfLabel = new javax.swing.JLabel();
        perfTF = new javax.swing.JTextField();
        browseTab = new javax.swing.JPanel();
        bOrganizeTabbedPane = new javax.swing.JTabbedPane();
        bFilterScrollTab = new javax.swing.JScrollPane();
        bFilterPanel = new javax.swing.JPanel();
        bUsedPanel = new javax.swing.JPanel();
        bUsedYesCB = new javax.swing.JCheckBox();
        bUsedNoCB = new javax.swing.JCheckBox();
        bDifficultyPanel = new javax.swing.JPanel();
        bDiffEasyCb = new javax.swing.JCheckBox();
        bDiffMedCB = new javax.swing.JCheckBox();
        bDiffHardCB = new javax.swing.JCheckBox();
        bCoursePanel = new javax.swing.JPanel();
        bCourseComboBox = new javax.swing.JComboBox<>();
        bTopicPanel = new javax.swing.JPanel();
        bTopicComboBox = new javax.swing.JComboBox<>();
        bSubtopicPanel = new javax.swing.JPanel();
        bSubtopicComboBox = new javax.swing.JComboBox<>();
        bSortTab = new javax.swing.JPanel();
        sortRB1 = new javax.swing.JRadioButton();
        sortRB2 = new javax.swing.JRadioButton();
        sortRB3 = new javax.swing.JRadioButton();
        sortRB4 = new javax.swing.JRadioButton();
        sortRB5 = new javax.swing.JRadioButton();
        sortRB6 = new javax.swing.JRadioButton();
        sortRB7 = new javax.swing.JRadioButton();
        sortRB8 = new javax.swing.JRadioButton();
        sortRB9 = new javax.swing.JRadioButton();
        sortRB10 = new javax.swing.JRadioButton();
        sortRB11 = new javax.swing.JRadioButton();
        searchPanel = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resultsScrollPane = new javax.swing.JScrollPane();
        resultsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.BorderLayout());

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        headerPanel.add(returnButton, java.awt.BorderLayout.LINE_START);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        headerPanel.add(helpButton, java.awt.BorderLayout.LINE_END);

        questionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionsLabel.setText("Questions");
        headerPanel.add(questionsLabel, java.awt.BorderLayout.CENTER);

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        manageControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        newButton.setText("New");
        manageControlsPanel.add(newButton);

        saveButton.setText("Save");
        manageControlsPanel.add(saveButton);

        clearButton.setText("Clear");
        manageControlsPanel.add(clearButton);

        deleteButton.setText("Delete");
        manageControlsPanel.add(deleteButton);

        manageQuestionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Question"));

        questionTF.setText("Question Text");

        qImageCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qImageCBActionPerformed(evt);
            }
        });

        qImageButton.setText("Choose Image");

        imagePathTF.setEditable(false);
        imagePathTF.setText("Image Path");
        imagePathTF.setFocusable(false);

        javax.swing.GroupLayout manageQuestionPanelLayout = new javax.swing.GroupLayout(manageQuestionPanel);
        manageQuestionPanel.setLayout(manageQuestionPanelLayout);
        manageQuestionPanelLayout.setHorizontalGroup(
            manageQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageQuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionTF)
                    .addGroup(manageQuestionPanelLayout.createSequentialGroup()
                        .addComponent(qImageCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qImageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagePathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        manageQuestionPanelLayout.setVerticalGroup(
            manageQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageQuestionPanelLayout.createSequentialGroup()
                .addComponent(questionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(qImageCB)
                    .addComponent(qImageButton)
                    .addComponent(imagePathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        manageAnswersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Answers"));

        ansTF1.setText("Answer 1");
        ansTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTF1ActionPerformed(evt);
            }
        });

        ansImageButton1.setText("Choose Image");

        ansTF2.setText("Answer 2");
        ansTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTF2ActionPerformed(evt);
            }
        });

        ansImageButton2.setText("Choose Image");

        ansTF3.setText("Answer 3");
        ansTF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTF3ActionPerformed(evt);
            }
        });

        ansImageButton3.setText("Choose Image");

        ansTF4.setText("Answer 4");
        ansTF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTF4ActionPerformed(evt);
            }
        });

        ansImageButton4.setText("Choose Image");

        javax.swing.GroupLayout manageAnswersPanelLayout = new javax.swing.GroupLayout(manageAnswersPanel);
        manageAnswersPanel.setLayout(manageAnswersPanelLayout);
        manageAnswersPanelLayout.setHorizontalGroup(
            manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                        .addComponent(ansRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansTF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageCB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageButton1))
                    .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                        .addComponent(ansRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansTF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageCB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageButton4))
                    .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                        .addComponent(ansRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansTF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageCB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageButton2))
                    .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                        .addComponent(ansRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansTF3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageCB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImageButton3)))
                .addContainerGap())
        );
        manageAnswersPanelLayout.setVerticalGroup(
            manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAnswersPanelLayout.createSequentialGroup()
                .addGroup(manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ansRadioButton1)
                    .addComponent(ansTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansImageButton1)
                    .addComponent(ansImageCB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ansRadioButton2)
                    .addComponent(ansTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansImageButton2)
                    .addComponent(ansImageCB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ansRadioButton3)
                    .addComponent(ansTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansImageButton3)
                    .addComponent(ansImageCB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageAnswersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ansRadioButton4)
                    .addComponent(ansTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansImageButton4)
                    .addComponent(ansImageCB4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageTagsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tags"));

        courseLabel.setText("Course:");

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "course1", "course2", "course3", "course4" }));

        topicLabel.setText("Topic:");

        topicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "topic1", "topic2", "topic3", "topic4" }));

        subtopicLabel.setText("Subtopic:");

        subtopicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "subtopic1", "subtopic2", "subtopic3", "subtopic4" }));

        difficultyLabel.setText("Difficulty:");

        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));

        javax.swing.GroupLayout tagsEditablePanelLayout = new javax.swing.GroupLayout(tagsEditablePanel);
        tagsEditablePanel.setLayout(tagsEditablePanelLayout);
        tagsEditablePanelLayout.setHorizontalGroup(
            tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagsEditablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtopicLabel)
                    .addComponent(courseLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(topicLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(difficultyLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tagsEditablePanelLayout.setVerticalGroup(
            tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tagsEditablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLabel)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicLabel)
                    .addComponent(topicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtopicLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateCreatedLabel.setText("Date Created:");

        dateCreatedTF.setEditable(false);
        dateCreatedTF.setText("DD/MM/YYYY");
        dateCreatedTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCreatedTFActionPerformed(evt);
            }
        });

        dateEditedLabel.setText("Last Edited:");

        dateEditedTF.setEditable(false);
        dateEditedTF.setText("DD/MM/YYYY");

        dateUsedLabel.setText("Last Used:");

        dateUsedTF.setEditable(false);
        dateUsedTF.setText("DD/MM/YYYY");

        usedCountLabel.setText("Times Used:");

        usedCountTF.setEditable(false);
        usedCountTF.setText("Count");

        perfLabel.setText("Performance:");

        perfTF.setEditable(false);
        perfTF.setText("Percentage");

        javax.swing.GroupLayout tagsNonEditablePanelLayout = new javax.swing.GroupLayout(tagsNonEditablePanel);
        tagsNonEditablePanel.setLayout(tagsNonEditablePanelLayout);
        tagsNonEditablePanelLayout.setHorizontalGroup(
            tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagsNonEditablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usedCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(perfLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateUsedLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateEditedLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateCreatedLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateCreatedTF)
                    .addComponent(dateEditedTF)
                    .addComponent(dateUsedTF)
                    .addComponent(usedCountTF)
                    .addComponent(perfTF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tagsNonEditablePanelLayout.setVerticalGroup(
            tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagsNonEditablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateCreatedLabel)
                    .addComponent(dateCreatedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateEditedLabel)
                    .addComponent(dateEditedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateUsedLabel)
                    .addComponent(dateUsedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usedCountLabel)
                    .addComponent(usedCountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tagsNonEditablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfLabel)
                    .addComponent(perfTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manageTagsPanelLayout = new javax.swing.GroupLayout(manageTagsPanel);
        manageTagsPanel.setLayout(manageTagsPanelLayout);
        manageTagsPanelLayout.setHorizontalGroup(
            manageTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTagsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tagsEditablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagsFiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagsNonEditablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageTagsPanelLayout.setVerticalGroup(
            manageTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageTagsPanelLayout.createSequentialGroup()
                .addGroup(manageTagsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagsEditablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagsFiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tagsNonEditablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageScrollContentPanelLayout = new javax.swing.GroupLayout(manageScrollContentPanel);
        manageScrollContentPanel.setLayout(manageScrollContentPanelLayout);
        manageScrollContentPanelLayout.setHorizontalGroup(
            manageScrollContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageScrollContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageScrollContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageTagsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAnswersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        manageScrollContentPanelLayout.setVerticalGroup(
            manageScrollContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageScrollContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAnswersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageTagsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        manageScrollTab.setViewportView(manageScrollContentPanel);

        questionsTabbedPane.addTab("Manage", manageScrollTab);

        bFilterScrollTab.setBorder(null);

        bUsedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Used"));

        bUsedYesCB.setText("Yes");

        bUsedNoCB.setText("No");

        javax.swing.GroupLayout bUsedPanelLayout = new javax.swing.GroupLayout(bUsedPanel);
        bUsedPanel.setLayout(bUsedPanelLayout);
        bUsedPanelLayout.setHorizontalGroup(
            bUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bUsedPanelLayout.createSequentialGroup()
                .addGroup(bUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bUsedYesCB)
                    .addComponent(bUsedNoCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bUsedPanelLayout.setVerticalGroup(
            bUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bUsedPanelLayout.createSequentialGroup()
                .addComponent(bUsedYesCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUsedNoCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bDifficultyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Difficulty"));

        bDiffEasyCb.setText("Easy");

        bDiffMedCB.setText("Medium");

        bDiffHardCB.setText("Hard");

        javax.swing.GroupLayout bDifficultyPanelLayout = new javax.swing.GroupLayout(bDifficultyPanel);
        bDifficultyPanel.setLayout(bDifficultyPanelLayout);
        bDifficultyPanelLayout.setHorizontalGroup(
            bDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDifficultyPanelLayout.createSequentialGroup()
                .addGroup(bDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDiffEasyCb)
                    .addComponent(bDiffMedCB)
                    .addComponent(bDiffHardCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bDifficultyPanelLayout.setVerticalGroup(
            bDifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDifficultyPanelLayout.createSequentialGroup()
                .addComponent(bDiffEasyCb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDiffMedCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDiffHardCB)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        bCoursePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));

        bCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        javax.swing.GroupLayout bCoursePanelLayout = new javax.swing.GroupLayout(bCoursePanel);
        bCoursePanel.setLayout(bCoursePanelLayout);
        bCoursePanelLayout.setHorizontalGroup(
            bCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCourseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bCoursePanelLayout.setVerticalGroup(
            bCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bTopicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Topic"));

        bTopicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Topic 1", "Topic 2", "Topic 3", "Topic 4" }));

        javax.swing.GroupLayout bTopicPanelLayout = new javax.swing.GroupLayout(bTopicPanel);
        bTopicPanel.setLayout(bTopicPanelLayout);
        bTopicPanelLayout.setHorizontalGroup(
            bTopicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bTopicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTopicComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bTopicPanelLayout.setVerticalGroup(
            bTopicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bTopicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bSubtopicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sub-Topic"));

        bSubtopicComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub-Topic 1", "Sub-Topic 2", "Sub-Topic 3", "Sub-Topic 4" }));
        bSubtopicComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubtopicComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bSubtopicPanelLayout = new javax.swing.GroupLayout(bSubtopicPanel);
        bSubtopicPanel.setLayout(bSubtopicPanelLayout);
        bSubtopicPanelLayout.setHorizontalGroup(
            bSubtopicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSubtopicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bSubtopicComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bSubtopicPanelLayout.setVerticalGroup(
            bSubtopicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSubtopicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bSubtopicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bFilterPanelLayout = new javax.swing.GroupLayout(bFilterPanel);
        bFilterPanel.setLayout(bFilterPanelLayout);
        bFilterPanelLayout.setHorizontalGroup(
            bFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSubtopicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDifficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTopicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bFilterPanelLayout.setVerticalGroup(
            bFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bUsedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDifficultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCoursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTopicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSubtopicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bFilterScrollTab.setViewportView(bFilterPanel);

        bOrganizeTabbedPane.addTab("Filter", bFilterScrollTab);

        sortRB1.setSelected(true);
        sortRB1.setText("Default");

        sortRB2.setText("Images First");
        sortRB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRB2ActionPerformed(evt);
            }
        });

        sortRB3.setText("Text First");

        sortRB4.setText("Last Used (Oldest First)");
        sortRB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortRB4ActionPerformed(evt);
            }
        });

        sortRB5.setText("Last Used (Newest First)");

        sortRB6.setText("Date Created (Oldest First)");

        sortRB7.setText("Date Created (Newest First)");

        sortRB8.setText("Times Used (Least First)");

        sortRB9.setText("Times Used (Most First)");

        sortRB10.setText("Difficulty (Easy First)");

        sortRB11.setText("Difficulty (Hard First)");

        javax.swing.GroupLayout bSortTabLayout = new javax.swing.GroupLayout(bSortTab);
        bSortTab.setLayout(bSortTabLayout);
        bSortTabLayout.setHorizontalGroup(
            bSortTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSortTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bSortTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortRB1)
                    .addComponent(sortRB2)
                    .addComponent(sortRB3)
                    .addComponent(sortRB4)
                    .addComponent(sortRB5)
                    .addComponent(sortRB6)
                    .addComponent(sortRB7)
                    .addComponent(sortRB8)
                    .addComponent(sortRB9)
                    .addComponent(sortRB10)
                    .addComponent(sortRB11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bSortTabLayout.setVerticalGroup(
            bSortTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSortTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sortRB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sortRB11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bOrganizeTabbedPane.addTab("Sort", bSortTab);

        searchPanel.setLayout(new java.awt.BorderLayout());

        searchTF.setText("Search...");
        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });
        searchPanel.add(searchTF, java.awt.BorderLayout.CENTER);

        searchButton.setText("Search");
        searchPanel.add(searchButton, java.awt.BorderLayout.LINE_END);

        resultsPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        resultsScrollPane.setViewportView(resultsPanel);

        javax.swing.GroupLayout browseTabLayout = new javax.swing.GroupLayout(browseTab);
        browseTab.setLayout(browseTabLayout);
        browseTabLayout.setHorizontalGroup(
            browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOrganizeTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        browseTabLayout.setVerticalGroup(
            browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOrganizeTabbedPane)
                    .addGroup(browseTabLayout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        questionsTabbedPane.addTab("Browse", browseTab);

        add(questionsTabbedPane, java.awt.BorderLayout.CENTER);
        questionsTabbedPane.getAccessibleContext().setAccessibleName("questionsTabs");
    }// </editor-fold>//GEN-END:initComponents

    private void qImageCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qImageCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qImageCBActionPerformed

    private void ansTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTF1ActionPerformed

    private void ansTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTF2ActionPerformed

    private void ansTF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTF3ActionPerformed

    private void ansTF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTF4ActionPerformed

    private void dateCreatedTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCreatedTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateCreatedTFActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    private void bSubtopicComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubtopicComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSubtopicComboBoxActionPerformed

    private void sortRB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortRB2ActionPerformed

    private void sortRB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortRB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortRB4ActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        CardLayout layout = (CardLayout) frame.getContentPane().getLayout();
        layout.show(frame.getContentPane(), "Home");
    }//GEN-LAST:event_returnButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        new Help(null, true, 2);
    }//GEN-LAST:event_helpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ansImageButton1;
    private javax.swing.JButton ansImageButton2;
    private javax.swing.JButton ansImageButton3;
    private javax.swing.JButton ansImageButton4;
    private javax.swing.JCheckBox ansImageCB1;
    private javax.swing.JCheckBox ansImageCB2;
    private javax.swing.JCheckBox ansImageCB3;
    private javax.swing.JCheckBox ansImageCB4;
    private javax.swing.JRadioButton ansRadioButton1;
    private javax.swing.JRadioButton ansRadioButton2;
    private javax.swing.JRadioButton ansRadioButton3;
    private javax.swing.JRadioButton ansRadioButton4;
    private javax.swing.JTextField ansTF1;
    private javax.swing.JTextField ansTF2;
    private javax.swing.JTextField ansTF3;
    private javax.swing.JTextField ansTF4;
    private javax.swing.JComboBox<String> bCourseComboBox;
    private javax.swing.JPanel bCoursePanel;
    private javax.swing.JCheckBox bDiffEasyCb;
    private javax.swing.JCheckBox bDiffHardCB;
    private javax.swing.JCheckBox bDiffMedCB;
    private javax.swing.JPanel bDifficultyPanel;
    private javax.swing.JPanel bFilterPanel;
    private javax.swing.JScrollPane bFilterScrollTab;
    private javax.swing.JTabbedPane bOrganizeTabbedPane;
    private javax.swing.JPanel bSortTab;
    private javax.swing.JComboBox<String> bSubtopicComboBox;
    private javax.swing.JPanel bSubtopicPanel;
    private javax.swing.JComboBox<String> bTopicComboBox;
    private javax.swing.JPanel bTopicPanel;
    private javax.swing.JCheckBox bUsedNoCB;
    private javax.swing.JPanel bUsedPanel;
    private javax.swing.JCheckBox bUsedYesCB;
    private javax.swing.JPanel browseTab;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel dateCreatedLabel;
    private javax.swing.JTextField dateCreatedTF;
    private javax.swing.JLabel dateEditedLabel;
    private javax.swing.JTextField dateEditedTF;
    private javax.swing.JLabel dateUsedLabel;
    private javax.swing.JTextField dateUsedTF;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> difficultyComboBox;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JTextField imagePathTF;
    private javax.swing.JPanel manageAnswersPanel;
    private javax.swing.JPanel manageControlsPanel;
    private javax.swing.JPanel manageQuestionPanel;
    private javax.swing.JPanel manageScrollContentPanel;
    private javax.swing.JScrollPane manageScrollTab;
    private javax.swing.JPanel manageTagsPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel perfLabel;
    private javax.swing.JTextField perfTF;
    private javax.swing.JButton qImageButton;
    private javax.swing.JCheckBox qImageCB;
    private javax.swing.JTextField questionTF;
    private javax.swing.JLabel questionsLabel;
    private javax.swing.JTabbedPane questionsTabbedPane;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JScrollPane resultsScrollPane;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTF;
    private javax.swing.JRadioButton sortRB1;
    private javax.swing.JRadioButton sortRB10;
    private javax.swing.JRadioButton sortRB11;
    private javax.swing.JRadioButton sortRB2;
    private javax.swing.JRadioButton sortRB3;
    private javax.swing.JRadioButton sortRB4;
    private javax.swing.JRadioButton sortRB5;
    private javax.swing.JRadioButton sortRB6;
    private javax.swing.JRadioButton sortRB7;
    private javax.swing.JRadioButton sortRB8;
    private javax.swing.JRadioButton sortRB9;
    private javax.swing.JComboBox<String> subtopicComboBox;
    private javax.swing.JLabel subtopicLabel;
    private javax.swing.JPanel tagsEditablePanel;
    private javax.swing.Box.Filler tagsFiller;
    private javax.swing.JPanel tagsNonEditablePanel;
    private javax.swing.JComboBox<String> topicComboBox;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JLabel usedCountLabel;
    private javax.swing.JTextField usedCountTF;
    // End of variables declaration//GEN-END:variables
}
